import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { mkdirSync, writeFileSync, chmodSync, rmSync } from 'node:fs';

// Auto-start installer for the snapstack server, as a package subcommand
// (`snapstack-server install` / `uninstall`). Replaces the old git-clone-era
// deploy/install-*.{sh,ps1} scripts: there is no checkout to run a script from
// when the package comes from npm, so the logic lives in the package itself.
//
// Update model — a mirror of the old `git pull` + `node` launcher: each (re)start
// does a best-effort `npm install --prefix <appDir> snapstack-server@latest`,
// then runs the copy already installed under <appDir>. The run step never needs
// the network, so capture intake survives an offline boot (once seeded once).
//
// The content generators (launcherSh / launcherPs1 / plist / systemdUnit) are
// pure functions so they can be unit-tested without touching the real system.

const PKG = 'snapstack-server';
const LABEL = 'com.snapstack.server'; // macOS launchd label
const UNIT = 'snapstack.service'; // systemd --user unit name
const TASK = 'snapstack'; // Windows scheduled-task name

/** Stable per-user install dir. */
export function appDir(platform = process.platform, env = process.env, home = os.homedir()) {
  if (platform === 'darwin') return path.join(home, 'Library', 'Application Support', 'snapstack');
  if (platform === 'win32') return path.join(env.LOCALAPPDATA || path.join(home, 'AppData', 'Local'), 'snapstack');
  return path.join(env.XDG_DATA_HOME || path.join(home, '.local', 'share'), 'snapstack');
}

/** Absolute dir holding node + npm — auto-start units run with a minimal PATH. */
export function nodeBinDir(execPath = process.execPath) {
  return path.dirname(execPath);
}

function launcherPath(dir, platform = process.platform) {
  return path.join(dir, platform === 'win32' ? 'snapstack-launch.ps1' : 'snapstack-launch.sh');
}

// --- content generators (pure) --------------------------------------------

/** POSIX launcher: best-effort self-update, then run the local install. */
export function launcherSh({ dir, binDir }) {
  return `#!/bin/sh
# snapstack launcher — generated by 'snapstack-server install'. Do not edit.
# Best-effort self-update, then run from the local install (offline-safe: if the
# update fails, e.g. offline, the previously installed copy still runs).
set -u
export PATH="${binDir}:$PATH"
PREFIX="${dir}"
npm install --prefix "$PREFIX" ${PKG}@latest >/dev/null 2>&1 || true
exec "$PREFIX/node_modules/.bin/snapstack-server"
`;
}

/** Windows launcher: same contract as launcherSh. */
export function launcherPs1({ dir, binDir }) {
  return `# snapstack launcher - generated by 'snapstack-server install'. Do not edit.
# Best-effort self-update, then run from the local install (offline-safe).
$ErrorActionPreference = 'SilentlyContinue'
$env:Path = "${binDir};$env:Path"
$prefix = "${dir}"
npm install --prefix $prefix ${PKG}@latest *> $null
& "${binDir}\\node.exe" "$prefix\\node_modules\\snapstack-server\\snapstack-server.js"
`;
}

/**
 * VBScript shim that runs the PS1 launcher silently.
 * wscript.exe is a GUI host (no console of its own). WshShell.Run with
 * window style 0 (SW_HIDE) hides every child window at the Win32 level —
 * npm.cmd, cmd.exe, node.exe — regardless of -WindowStyle Hidden limits.
 * bWaitOnReturn=True keeps wscript alive while the server runs so the
 * scheduled-task restart settings remain effective.
 */
export function launcherVbs({ launcher }) {
  // Chr(34) = double-quote — avoids VBScript "" escaping confusion.
  return `' snapstack silent launcher - generated by 'snapstack-server install'. Do not edit.
CreateObject("WScript.Shell").Run "powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File " & Chr(34) & "${launcher}" & Chr(34), 0, True
`;
}

/** macOS launchd LaunchAgent: start at login, restart on crash. */
export function plist({ launcher }) {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/sh</string>
    <string>${launcher}</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>/tmp/snapstack.out.log</string>
  <key>StandardErrorPath</key>
  <string>/tmp/snapstack.err.log</string>
</dict>
</plist>
`;
}

/** Linux systemd --user unit: start at login, restart on failure. */
export function systemdUnit({ launcher }) {
  return `[Unit]
Description=SnapStack capture + MCP server (local)
After=network.target

[Service]
ExecStart=/usr/bin/env sh ${launcher}
Restart=on-failure
RestartSec=2

[Install]
WantedBy=default.target
`;
}

// --- side effects ----------------------------------------------------------

// Seed the stable install so the very first boot — possibly offline — has a copy
// to run. Best-effort: a failure (offline, or package not yet published) is
// reported but never aborts; the launcher's update step self-heals on a later
// online (re)start.
function seed(dir, binDir, platform) {
  const npm = platform === 'win32' ? 'npm.cmd' : 'npm';
  const env = { ...process.env, PATH: `${binDir}${path.delimiter}${process.env.PATH || ''}` };
  const r = spawnSync(npm, ['install', '--prefix', dir, `${PKG}@latest`], { stdio: 'inherit', env });
  if (r.status !== 0) {
    console.warn(`warning: could not seed ${dir} (offline, or ${PKG} not yet published).`);
    console.warn('  The launcher will self-install on the first online (re)start.');
  }
}

function writeLauncher(dir, binDir, platform) {
  const file = launcherPath(dir, platform);
  const body = platform === 'win32' ? launcherPs1({ dir, binDir }) : launcherSh({ dir, binDir });
  writeFileSync(file, body);
  if (platform !== 'win32') chmodSync(file, 0o755);
  return file;
}

function installMac(dir, binDir) {
  const launcher = writeLauncher(dir, binDir, 'darwin');
  const plistPath = path.join(os.homedir(), 'Library', 'LaunchAgents', `${LABEL}.plist`);
  mkdirSync(path.dirname(plistPath), { recursive: true });
  writeFileSync(plistPath, plist({ launcher }));
  spawnSync('launchctl', ['unload', plistPath], { stdio: 'ignore' });
  spawnSync('launchctl', ['load', plistPath], { stdio: 'inherit' });
  console.log(`Installed launchd agent: ${plistPath}`);
  console.log(`  launcher : ${launcher}`);
  console.log(`  logs     : /tmp/snapstack.out.log  /tmp/snapstack.err.log`);
  console.log(`Uninstall: snapstack-server uninstall`);
}

function installLinux(dir, binDir) {
  const launcher = writeLauncher(dir, binDir, 'linux');
  const unitDir = path.join(process.env.XDG_CONFIG_HOME || path.join(os.homedir(), '.config'), 'systemd', 'user');
  const unitPath = path.join(unitDir, UNIT);
  mkdirSync(unitDir, { recursive: true });
  writeFileSync(unitPath, systemdUnit({ launcher }));
  spawnSync('systemctl', ['--user', 'daemon-reload'], { stdio: 'inherit' });
  spawnSync('systemctl', ['--user', 'enable', '--now', UNIT], { stdio: 'inherit' });
  console.log(`Installed systemd --user unit: ${unitPath}`);
  console.log(`  launcher : ${launcher}`);
  console.log(`  status   : systemctl --user status snapstack`);
  console.log(`Uninstall: snapstack-server uninstall`);
}

function installWin(dir, binDir) {
  const launcher = writeLauncher(dir, binDir, 'win32');
  const vbs = path.join(dir, 'snapstack-launch.vbs');
  writeFileSync(vbs, launcherVbs({ launcher }));
  const ps = [
    `$a = New-ScheduledTaskAction -Execute 'wscript.exe' -Argument '/b "${vbs}"'`,
    `$t = New-ScheduledTaskTrigger -AtLogOn`,
    `$s = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 1)`,
    `Register-ScheduledTask -TaskName '${TASK}' -Action $a -Trigger $t -Settings $s -Force | Out-Null`,
    `Start-ScheduledTask -TaskName '${TASK}'`,
  ].join('; ');
  spawnSync('powershell.exe', ['-NoProfile', '-Command', ps], { stdio: 'inherit' });
  console.log(`Installed scheduled task: ${TASK}`);
  console.log(`  launcher : ${launcher}`);
  console.log(`Uninstall: snapstack-server uninstall`);
}

/** Seed the stable install, write the launcher, and register the auto-start unit. */
export function install({ platform = process.platform } = {}) {
  const dir = appDir(platform);
  const binDir = nodeBinDir();
  mkdirSync(dir, { recursive: true });
  seed(dir, binDir, platform);
  if (platform === 'darwin') return installMac(dir, binDir);
  if (platform === 'win32') return installWin(dir, binDir);
  return installLinux(dir, binDir);
}

/** Remove the auto-start unit. Leaves <appDir> in place (purge it by hand). */
export function uninstall({ platform = process.platform } = {}) {
  const dir = appDir(platform);
  if (platform === 'darwin') {
    const plistPath = path.join(os.homedir(), 'Library', 'LaunchAgents', `${LABEL}.plist`);
    spawnSync('launchctl', ['unload', plistPath], { stdio: 'ignore' });
    rmSync(plistPath, { force: true });
    console.log(`Removed launchd agent: ${plistPath}`);
  } else if (platform === 'win32') {
    spawnSync('powershell.exe', ['-NoProfile', '-Command', `Unregister-ScheduledTask -TaskName '${TASK}' -Confirm:$false`], { stdio: 'inherit' });
    console.log(`Removed scheduled task: ${TASK}`);
  } else {
    const unitPath = path.join(process.env.XDG_CONFIG_HOME || path.join(os.homedir(), '.config'), 'systemd', 'user', UNIT);
    spawnSync('systemctl', ['--user', 'disable', '--now', UNIT], { stdio: 'inherit' });
    rmSync(unitPath, { force: true });
    spawnSync('systemctl', ['--user', 'daemon-reload'], { stdio: 'inherit' });
    console.log(`Removed systemd --user unit: ${unitPath}`);
  }
  console.log(`Kept the install at ${dir} — remove it by hand to fully uninstall.`);
}
