import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { mkdirSync, writeFileSync, chmodSync, rmSync, existsSync } from 'node:fs';

const PKG = 'snapstack-server'; // npm package name (the single bin is `snapstack`)
const LABEL = 'com.snapstack.server'; // macOS launchd label
const UNIT = 'snapstack.service'; // systemd --user unit name
const TASK = 'snapstack'; // Windows scheduled-task name

/** Stable per-user install dir (holds the self-updating runtime copy). */
export function appDir(platform = process.platform, env = process.env, home = os.homedir()) {
  if (platform === 'darwin') return path.join(home, 'Library', 'Application Support', 'snapstack');
  if (platform === 'win32') return path.join(env.LOCALAPPDATA || path.join(home, 'AppData', 'Local'), 'snapstack');
  return path.join(env.XDG_DATA_HOME || path.join(home, '.local', 'share'), 'snapstack');
}

/** Absolute dir holding node + npm — auto-start units run with a minimal PATH. */
export function nodeBinDir(execPath = process.execPath) {
  return path.dirname(execPath);
}

/** macOS LaunchAgent path for the current user. */
function plistPath(home = os.homedir()) {
  return path.join(home, 'Library', 'LaunchAgents', `${LABEL}.plist`);
}

/** systemd --user unit path for the current user. */
function unitPath(env = process.env, home = os.homedir()) {
  return path.join(env.XDG_CONFIG_HOME || path.join(home, '.config'), 'systemd', 'user', UNIT);
}

function launcherPath(dir, platform = process.platform) {
  return path.join(dir, platform === 'win32' ? 'snapstack-launch.ps1' : 'snapstack-launch.sh');
}

/** launchd domain target for the GUI session of the current user. */
function guiTarget() {
  return `gui/${process.getuid?.() ?? ''}`;
}

/** POSIX launcher: best-effort self-update, then run the local install. */
export function launcherSh({ dir, binDir }) {
  return `#!/bin/sh
# snapstack launcher — generated by 'snapstack enable'. Do not edit.
# Best-effort self-update, then run from the local install (offline-safe: if the
# update fails, e.g. offline, the previously installed copy still runs).
set -u
export PATH="${binDir}:$PATH"
PREFIX="${dir}"
npm install --prefix "$PREFIX" ${PKG}@latest >/dev/null 2>&1 || true
exec "$PREFIX/node_modules/.bin/snapstack" run
`;
}

/** Windows launcher: same contract as launcherSh. */
export function launcherPs1({ dir, binDir }) {
  return `# snapstack launcher - generated by 'snapstack enable'. Do not edit.
# Best-effort self-update, then run from the local install (offline-safe).
$ErrorActionPreference = 'SilentlyContinue'
$env:Path = "${binDir};$env:Path"
$prefix = "${dir}"
npm install --prefix $prefix ${PKG}@latest *> $null
& "${binDir}\\node.exe" "$prefix\\node_modules\\${PKG}\\snapstack.js" run
`;
}

/**
 * VBScript shim that runs the PS1 launcher silently.
 * wscript.exe is a GUI host (no console of its own). WshShell.Run with
 * window style 0 (SW_HIDE) hides every child window at the Win32 level —
 * npm.cmd, cmd.exe, node.exe — regardless of -WindowStyle Hidden limits.
 * bWaitOnReturn=True keeps wscript alive while the server runs so the
 * scheduled-task restart settings remain effective.
 */
export function launcherVbs({ launcher }) {
  return `' snapstack silent launcher - generated by 'snapstack enable'. Do not edit.
CreateObject("WScript.Shell").Run "powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File " & Chr(34) & "${launcher}" & Chr(34), 0, True
`;
}

/** macOS launchd LaunchAgent: start at login, restart on crash. */
export function plist({ launcher }) {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/sh</string>
    <string>${launcher}</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>/tmp/snapstack.out.log</string>
  <key>StandardErrorPath</key>
  <string>/tmp/snapstack.err.log</string>
</dict>
</plist>
`;
}

/** Linux systemd --user unit: start at login, restart on failure. */
export function systemdUnit({ launcher }) {
  return `[Unit]
Description=SnapStack capture + MCP server (local)
After=network.target

[Service]
ExecStart=/usr/bin/env sh ${launcher}
Restart=on-failure
RestartSec=2

[Install]
WantedBy=default.target
`;
}

function seed(dir, binDir, platform) {
  const npm = platform === 'win32' ? 'npm.cmd' : 'npm';
  const env = { ...process.env, PATH: `${binDir}${path.delimiter}${process.env.PATH || ''}` };
  const r = spawnSync(npm, ['install', '--prefix', dir, `${PKG}@latest`], { stdio: 'inherit', env });
  if (r.status !== 0) {
    console.warn(`warning: could not seed ${dir} (offline, or ${PKG} not yet published).`);
    console.warn('  The launcher will self-install on the first online (re)start.');
  }
}

function writeLauncher(dir, binDir, platform) {
  const file = launcherPath(dir, platform);
  const body = platform === 'win32' ? launcherPs1({ dir, binDir }) : launcherSh({ dir, binDir });
  writeFileSync(file, body);
  if (platform !== 'win32') chmodSync(file, 0o755);
  return file;
}

function enableMac(dir, binDir) {
  const launcher = writeLauncher(dir, binDir, 'darwin');
  const file = plistPath();
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileSync(file, plist({ launcher }));
  spawnSync('launchctl', ['unload', file], { stdio: 'ignore' });
  spawnSync('launchctl', ['load', file], { stdio: 'inherit' });
  console.log(`Enabled launchd agent: ${file}`);
  console.log(`  launcher : ${launcher}`);
  console.log(`  logs     : /tmp/snapstack.out.log  /tmp/snapstack.err.log`);
  console.log(`Disable with: snapstack disable`);
}

function enableLinux(dir, binDir) {
  const launcher = writeLauncher(dir, binDir, 'linux');
  const file = unitPath();
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileSync(file, systemdUnit({ launcher }));
  spawnSync('systemctl', ['--user', 'daemon-reload'], { stdio: 'inherit' });
  spawnSync('systemctl', ['--user', 'enable', '--now', UNIT], { stdio: 'inherit' });
  console.log(`Enabled systemd --user unit: ${file}`);
  console.log(`  launcher : ${launcher}`);
  console.log(`  status   : systemctl --user status snapstack`);
  console.log(`Disable with: snapstack disable`);
}

function enableWin(dir, binDir) {
  const launcher = writeLauncher(dir, binDir, 'win32');
  const vbs = path.join(dir, 'snapstack-launch.vbs');
  writeFileSync(vbs, launcherVbs({ launcher }));
  const ps = [
    `$a = New-ScheduledTaskAction -Execute 'wscript.exe' -Argument '/b "${vbs}"'`,
    `$t = New-ScheduledTaskTrigger -AtLogOn`,
    `$s = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 1)`,
    `Register-ScheduledTask -TaskName '${TASK}' -Action $a -Trigger $t -Settings $s -Force | Out-Null`,
    `Start-ScheduledTask -TaskName '${TASK}'`,
  ].join('; ');
  spawnSync('powershell.exe', ['-NoProfile', '-Command', ps], { stdio: 'inherit' });
  console.log(`Enabled scheduled task: ${TASK}`);
  console.log(`  launcher : ${launcher}`);
  console.log(`Disable with: snapstack disable`);
}

/** Seed the stable install, write the launcher, and register the auto-start unit. */
export function enable({ platform = process.platform } = {}) {
  const dir = appDir(platform);
  const binDir = nodeBinDir();
  mkdirSync(dir, { recursive: true });
  seed(dir, binDir, platform);
  if (platform === 'darwin') return enableMac(dir, binDir);
  if (platform === 'win32') return enableWin(dir, binDir);
  return enableLinux(dir, binDir);
}

/** Remove the auto-start unit. Leaves <appDir> in place (purge it by hand). */
export function disable({ platform = process.platform } = {}) {
  const dir = appDir(platform);
  if (platform === 'darwin') {
    const file = plistPath();
    spawnSync('launchctl', ['unload', file], { stdio: 'ignore' });
    rmSync(file, { force: true });
    console.log(`Disabled launchd agent: ${file}`);
  } else if (platform === 'win32') {
    spawnSync('powershell.exe', ['-NoProfile', '-Command', `Unregister-ScheduledTask -TaskName '${TASK}' -Confirm:$false`], { stdio: 'inherit' });
    console.log(`Disabled scheduled task: ${TASK}`);
  } else {
    const file = unitPath();
    spawnSync('systemctl', ['--user', 'disable', '--now', UNIT], { stdio: 'inherit' });
    rmSync(file, { force: true });
    spawnSync('systemctl', ['--user', 'daemon-reload'], { stdio: 'inherit' });
    console.log(`Disabled systemd --user unit: ${file}`);
  }
  console.log(`Kept the install at ${dir} — remove it by hand to fully uninstall.`);
}

// --- transient control (this session) -------------------------------------
// `start`/`stop`/`restart` drive the OS service manager, not a raw PID: with
// KeepAlive (launchd) / Restart= (systemd) / RestartCount (task) the manager
// would otherwise just respawn a killed process. `stop` truly stops now; the
// service returns at next login or via `snapstack start`.

/** Run a service-manager command quietly; returns its exit status (or null). */
function run(cmd, args) {
  return spawnSync(cmd, args, { stdio: 'ignore' }).status;
}

export function start({ platform = process.platform } = {}) {
  if (platform === 'darwin') {
    run('launchctl', ['bootstrap', guiTarget(), plistPath()]); // load (ignore if already loaded)
    return run('launchctl', ['kickstart', `${guiTarget()}/${LABEL}`]) === 0;
  }
  if (platform === 'win32') return run('powershell.exe', ['-NoProfile', '-Command', `Start-ScheduledTask -TaskName '${TASK}'`]) === 0;
  return run('systemctl', ['--user', 'start', UNIT]) === 0;
}

export function stop({ platform = process.platform } = {}) {
  if (platform === 'darwin') return run('launchctl', ['bootout', `${guiTarget()}/${LABEL}`]) === 0;
  if (platform === 'win32') return run('powershell.exe', ['-NoProfile', '-Command', `Stop-ScheduledTask -TaskName '${TASK}'`]) === 0;
  return run('systemctl', ['--user', 'stop', UNIT]) === 0;
}

export function restart({ platform = process.platform } = {}) {
  if (platform === 'darwin') {
    if (run('launchctl', ['kickstart', '-k', `${guiTarget()}/${LABEL}`]) === 0) return true;
    return start({ platform }); // not loaded yet → load + start
  }
  if (platform === 'win32') {
    run('powershell.exe', ['-NoProfile', '-Command', `Stop-ScheduledTask -TaskName '${TASK}'`]);
    return run('powershell.exe', ['-NoProfile', '-Command', `Start-ScheduledTask -TaskName '${TASK}'`]) === 0;
  }
  return run('systemctl', ['--user', 'restart', UNIT]) === 0;
}

/**
 * Bring everything to the latest published version in one go: update the global
 * CLI (`npm i -g`), then restart the daemon so its appDir copy self-updates too
 * (the launcher runs `npm install --prefix <appDir> @latest` before exec). The
 * boot path is unchanged — only this interactive command touches the global CLI.
 */
export function update({ platform = process.platform } = {}) {
  const npm = platform === 'win32' ? 'npm.cmd' : 'npm';
  const env = { ...process.env, PATH: `${nodeBinDir()}${path.delimiter}${process.env.PATH || ''}` };
  // shell: true required on Windows so cmd.exe resolves .cmd scripts; on POSIX it's harmless.
  const r = spawnSync(npm, ['install', '-g', `${PKG}@latest`], { stdio: 'inherit', env, shell: platform === 'win32' });
  if (r.status !== 0) return { cliUpdated: false, restarted: false };
  if (!serviceStatus({ platform }).enabled) return { cliUpdated: true, restarted: false };
  return { cliUpdated: true, restarted: restart({ platform }) };
}

// --- introspection (drives the report's "Service" badge) ------------------

function out(cmd, args) {
  const r = spawnSync(cmd, args, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] });
  return { code: r.status, text: r.stdout || '' };
}

/**
 * Three facts about the auto-start service:
 * - enabled : will it launch at login? (unit/plist/task registered)
 * - running : is the manager running it right now?
 * - pid     : the running process id when known (null on Windows — the
 *             scheduled task does not surface it cheaply).
 * The "is the server actually answering" question is separate — that's /health.
 */
export function serviceStatus({ platform = process.platform } = {}) {
  if (platform === 'darwin') {
    const enabled = existsSync(plistPath());
    let running = false;
    let pid = null;
    if (enabled) {
      const r = out('launchctl', ['print', `${guiTarget()}/${LABEL}`]);
      running = r.code === 0 && /state\s*=\s*running/.test(r.text);
      if (running) {
        const m = /\bpid\s*=\s*(\d+)/.exec(r.text);
        pid = m ? Number(m[1]) : null;
      }
    }
    return { manager: 'launchd', target: LABEL, enabled, running, pid };
  }
  if (platform === 'win32') {
    const r = out('powershell.exe', ['-NoProfile', '-Command', `$t = Get-ScheduledTask -TaskName '${TASK}' -ErrorAction SilentlyContinue; if ($t) { $t.State }`]);
    const state = r.text.trim();
    return { manager: 'scheduled-task', target: TASK, enabled: state !== '' && state !== 'Disabled', running: state === 'Running', pid: null };
  }
  const en = out('systemctl', ['--user', 'is-enabled', UNIT]);
  const ac = out('systemctl', ['--user', 'is-active', UNIT]);
  const running = ac.text.trim() === 'active';
  let pid = null;
  if (running) {
    const n = parseInt(out('systemctl', ['--user', 'show', '-p', 'MainPID', '--value', UNIT]).text.trim(), 10);
    pid = n > 0 ? n : null;
  }
  return { manager: 'systemd', target: UNIT, enabled: en.text.trim() === 'enabled', running, pid };
}
